
var FLightDetails = {
	getFlightDetails: function() {
		var flightDetails=[
			{
				airline:"Emirates",
				serialNo:"A6-EWC",
				airdraftType:"777-200LR",
				img:"http://aviapix.ch/pics/FaAv/212-IMG_5275.jpg",
				logo:"https://pbs.twimg.com/profile_images/461440476696961024/FudoDgQK.png",
				gateId:"1",
				flightNo:"EK-568",
				arrivalFlightNo:"EK-567",
				origin:"Dubai",
				destination:"Dubai",
				operator:"Emirates",
				startTime:"16:30",
				endTime:"18:30",
				itenary:''
			},{
				airline:"Air India Express",
				serialNo:"VT-AXE",
				airdraftType:"737-800",
				img:"http://img.planespotters.net/photo/259000/original/VT-AXE-Air-India-Express-Boeing-737-800_PlanespottersNet_259358.jpg",
				logo:"https://c2.staticflickr.com/4/3081/2693517115_ebbb32668d.jpg",
				gateId:"4",
				flightNo:"AI-967",
				arrivalFlightNo:"AI-966",
				origin:"Sharjah (SHJ)",
				destination:"Sharjah (SHJ)",
				operator:"Air India Express",
				startTime:"14:35",
				endTime:"16:35",
				itenary:''
			},{
				airline:"Etihad Airways",
				serialNo:"A6-ETR",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/554000/original/A6-ETR-Etihad-Airways-Boeing-777-300_PlanespottersNet_554285.jpg",
				logo:"https://upload.wikimedia.org/wikipedia/commons/c/c5/EY-Etihad-Airways-new-logo-En.jpg",
				gateId:"1",
				flightNo:"EY-287",
				arrivalFlightNo:"EY-286",
				origin:"Abu Dhabi (AUH)",
				destination:"Abu Dhabi (AUH)",
				operator:"Etihad Airways",
				startTime:"08:00",
				endTime:"10:00",
				itenary:''
			},{
				airline:"Etihad Airways",
				serialNo:"A6-LRC",
				airdraftType:"777-200LR",
				img:"https://c2.staticflickr.com/8/7470/15667068154_39b5684257_b.jpg",
				logo:"https://upload.wikimedia.org/wikipedia/commons/c/c5/EY-Etihad-Airways-new-logo-En.jpg",
				gateId:"1",
				flightNo:"EY-281",
				arrivalFlightNo:"EY-81",
				origin:"Milan (MXP)",
				destination:"Abu Dhabi (AUH)",
				operator:"Etihad Airways",
				startTime:"14:00",
				endTime:"16:00",
				itenary:''
			},{
				airline:"Etihad Airways",
				serialNo:"A6-BLA",
				airdraftType:"787-9",
				img:"http://img.planespotters.net/photo/573000/original/A6-BLA-Etihad-Airways-Boeing-787-9-Dreamliner_PlanespottersNet_573449.jpg",
				logo:"https://upload.wikimedia.org/wikipedia/commons/c/c5/EY-Etihad-Airways-new-logo-En.jpg",
				gateId:"2",
				flightNo:"EY-80",
				arrivalFlightNo:"EY-280",
				origin:"Abu Dhabi (AUH)",
				destination:"Milan (MXP)",
				operator:"Etihad Airways",
				startTime:"14:05",
				endTime:"16:05",
				itenary:''
			},{
				airline:"Virgin Atlantic",
				serialNo:"G-VNEW",
				airdraftType:"787-9",
				img:"http://img.planespotters.net/photo/553000/original/G-VNEW-Virgin-Atlantic-Airways-Boeing-787-9-Dreamliner_PlanespottersNet_553205.jpg",
				logo:"https://worldairlinenews.files.wordpress.com/2014/10/virgin-atlantic-logo-large-1.jpg",
				gateId:"1",
				flightNo:"VS-300",
				arrivalFlightNo:"VS-299",
				origin:"London (LHR)",
				destination:"London (LHR)",
				operator:"Virgin Atlantic",
				startTime:"21:56",
				endTime:"23:56",
				itenary:''
			},{
				airline:"Virgin Australia",
				serialNo:"VH-VPH",
				airdraftType:"777-300ER",
				img:"http://img1.jetphotos.net:8080/img/4/2/8/5/52509_1337520582.jpg",
				logo:"https://lh3.ggpht.com/7ydNZbogRCsio7qpwRn0RcD4MHP1_-GTvKpHWb5HvM5mp4uibpGT30CnNX6E93bGIHqX=w300",
				gateId:"1",
				flightNo:"VA-5",
				arrivalFlightNo:"VA-4",
				origin:"Sydney (SYD)",
				destination:"Sydney (SYD)",
				operator:"Virgin Australia",
				startTime:"11:05",
				endTime:"13:05",
				itenary:''
			},{
				airline:"Cathay Pacific",
				serialNo:"B-KPA",
				airdraftType:"777-300ER",
				img:"http://cdn.airplane-pictures.net/images/uploaded-images/2011/8/24/152910.jpg",
				logo:"https://i.ytimg.com/i/DF__e4OyxESzW1snu1i0Bg/mq1.jpg?v=544df142",
				gateId:"2",
				flightNo:"CX-05",
				arrivalFlightNo:"CX-532",
				origin:"Hong Kong (HKG)",
				destination:"London (LHR)",
				operator:"British Airways",
				startTime:"08:02",
				endTime:"10:02",
				itenary:''
			},{
				airline:"Cathay Pacific",
				serialNo:"B-KPL",
				airdraftType:"777-300ER",
				img:"http://www.planes-international.com/CX-773-B-KPL-HKG-050910-1.jpg",
				logo:"https://i.ytimg.com/i/DF__e4OyxESzW1snu1i0Bg/mq1.jpg?v=544df142",
				gateId:"3",
				flightNo:"CX-533",
				arrivalFlightNo:"CX-06",
				origin:"London (LHR)",
				destination:"Hong Kong (HKG)",
				operator:"Cathay Pacific",
				startTime:"08:12",
				endTime:"10:12",
				itenary:''
			},
			{
				airline:"Cathay Pacific",
				serialNo:"B-KQX",
				airdraftType:"777-300ER",
				img:"https://worldairlinenews.files.wordpress.com/2015/05/cathay-pacific-777-300-b-kqx-94-our-50th-777-300ernose-pae-boeinglrw.jpg?w=625",
				logo:"https://i.ytimg.com/i/DF__e4OyxESzW1snu1i0Bg/mq1.jpg?v=544df142",
				gateId:"2",
				flightNo:"CX-07",
				arrivalFlightNo:"CX-534",
				origin:"Hong Kong (HKG)",
				destination:"Paris (CDG)",
				operator:"Cathay Pacific",
				startTime:"20:00",
				endTime:"22:00",
				itenary:''
			},
			{
				airline:"Cathay Pacific",
				serialNo:"B-KPB",
				airdraftType:"777-300ER",
				img:"https://c2.staticflickr.com/4/3668/11387233563_32cbc5bf67_b.jpg",
				logo:"https://i.ytimg.com/i/DF__e4OyxESzW1snu1i0Bg/mq1.jpg?v=544df142",
				gateId:"3",
				flightNo:"CX-535",
				arrivalFlightNo:"CX-08",
				origin:"Paris (CDG)",
				destination:"Hong Kong (HKG)",
				operator:"Cathay Pacific",
				startTime:"19:50",
				endTime:"21:50",
				itenary:''
			},{
				airline:"Japan Airlines",
				serialNo:"JA861J",
				airdraftType:"787-9",
				img:"http://airlinersgallery.smugmug.com/Airlines-Asia-2/Airlines-Asia2-FP/JAL-Japan-Airlines/i-NJVkvxC/0/S/JAL-Japan%20Airlines%20787-9%20JA861J%20(11)(Grd)%20PAE%20(RYK)(46)-S.jpg",
				logo:"http://www.britishairways.com/assets/images/information/logos/airline-logos/240x40-JAL-logo.png",
				gateId:"3",
				flightNo:"JL-740",
				arrivalFlightNo:"JL-739",
				origin:"Tokyo-Narita (NRT)",
				destination:"Tokyo-Narita (NRT)",
				operator:"Japan Airlines",
				startTime:"15:00",
				endTime:"17:00",
				itenary:''
			},{
				airline:"American Airlines",
				serialNo:"N718AN",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/562000/original/N718AN-American-Airlines-Boeing-777-300_PlanespottersNet_562779.jpg",
				logo:"http://bento.cdn.pbs.org/hostedbento-prod/filer_public/cci-nmdc-static/images/logos/american-airlines-logo.jpg",
				gateId:"2",
				flightNo:"AA-111",
				arrivalFlightNo:"AA-110",
				origin:"London(LHR)",
				destination:"London(LHR)",
				operator:"British Airways",
				startTime:"21:55",
				endTime:"23:55",
				itenary:''
			},{
				airline:"Qatar Airways",
				serialNo:"A7-BEA",
				airdraftType:"777-300ER",
				img:"http://cfile6.uf.tistory.com/image/2247A64354A6A62B2479F4",
				logo:"http://media3.fcbarcelona.com/media/asset_publics/resources/000/057/823/size_320x250/qatar_airways.v1372417001.jpg",
				gateId:"3",
				flightNo:"QR-846",
				arrivalFlightNo:"QR-572",
				origin:"Doha (DOH)",
				destination:"Kuala lumpur (KUL)",
				operator:"Malaysia Airlines",
				startTime:"17:20",
				endTime:"19:20",
				itenary:''
			},{
				airline:"Qatar Airways",
				serialNo:"A7-BAA",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/418000/original/A7-BAA-Qatar-Airways-Boeing-777-300_PlanespottersNet_418589.jpg",
				logo:"http://media3.fcbarcelona.com/media/asset_publics/resources/000/057/823/size_320x250/qatar_airways.v1372417001.jpg",
				gateId:"2",
				flightNo:"QR-573",
				arrivalFlightNo:"QR-847",
				origin:"Kuala lumpur (KUL)",
				destination:"Doha (DOH)",
				operator:"Qatar Airways",
				startTime:"16:26",
				endTime:"18:26",
				itenary:''
			},{
				airline:"Qatar Airways",
				serialNo:"A7-BCK",
				airdraftType:"787-8",
				img:"https://c2.staticflickr.com/4/3695/10962173236_50cc306068_b.jpg",
				logo:"http://media3.fcbarcelona.com/media/asset_publics/resources/000/057/823/size_320x250/qatar_airways.v1372417001.jpg",
				gateId:"3",
				flightNo:"QR-575",
				arrivalFlightNo:"QR-574",
				origin:"Doha (DOH)",
				destination:"Doha (DOH)",
				operator:"Qatar Airways",
				startTime:"21:58",
				endTime:"23:58",
				itenary:''
			},{
				airline:"Qatar Airways",
				serialNo:"A7-BBB",
				airdraftType:"777-200LR",
				img:"http://img.planespotters.net/photo/308000/original/A7-BBB-Qatar-Airways-Boeing-777-200_PlanespottersNet_308351.jpg",
				logo:"http://media3.fcbarcelona.com/media/asset_publics/resources/000/057/823/size_320x250/qatar_airways.v1372417001.jpg",
				gateId:"2",
				flightNo:"QR-577",
				arrivalFlightNo:"QR-923",
				origin:"Melbourne (MEL)",
				destination:"Doha (DOH)",
				operator:"Qatar Airways",
				startTime:"10:22",
				endTime:"12:22",
				itenary:''
			},{
				airline:"Qatar Airways",
				serialNo:"A7-ALA",
				airdraftType:"350-900",
				img:"http://img1.jetphotos.net:8080/img/6/3/4/0/17311_1422559043.jpg",
				logo:"http://media3.fcbarcelona.com/media/asset_publics/resources/000/057/823/size_320x250/qatar_airways.v1372417001.jpg",
				gateId:"3",
				flightNo:"QR-922",
				arrivalFlightNo:"QR-576",
				origin:"Doha (DOH)",
				destination:"Melbourne (MEL)",
				operator:"Qantas",
				startTime:"10:20",
				endTime:"12:20",
				itenary:''
			},{
				airline:"KLM",
				serialNo:"PH-BVN",
				airdraftType:"777-300ER",
				img:"http://painefield.info/images/kpae11030.png",
				logo:"http://cptdb.ca/wiki/images/8/85/KLM_LOGO_BY_KLM.jpg",
				gateId:"7",
				flightNo:"KL-0872",
				arrivalFlightNo:"KL-0871",
				origin:"Amsterdam (AMS)",
				destination:"Amsterdam (AMS)",
				operator:"KLM",
				startTime:"14:45",
				endTime:"16:45",
				itenary:''
			},{
				airline:"Air France",
				serialNo:"F-GSQF",
				airdraftType:"777-300ER",
				img:"https://planefinder.net/images/5983902:Photo:472003.jpg",
				logo:"http://thejetsetpets.com/wp-content/uploads/2012/07/air-france-logo-abbreviated.jpg",
				gateId:"7",
				flightNo:"AF-491",
				arrivalFlightNo:"AF-192",
				origin:"Paris(CDG)",
				destination:"Jakarta (CGK)",
				operator:"Air France",
				startTime:"08:17",
				endTime:"10:17",
				itenary:''
			},{
				airline:"Air France",
				serialNo:"F-GZNE",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/390000/original/F-GZNE-Air-France-Boeing-777-300_PlanespottersNet_390589.jpg",
				logo:"http://thejetsetpets.com/wp-content/uploads/2012/07/air-france-logo-abbreviated.jpg",
				gateId:"7",
				flightNo:"AF-193",
				arrivalFlightNo:"AF-492",
				origin:"Jakarta (CGK)",
				destination:"Paris (CDG)",
				operator:"Air France",
				startTime:"10:22",
				endTime:"12:22",
				itenary:''
			},{
				airline:"Air France",
				serialNo:"F-GZNI",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/195000/original/F-GZNI-Air-France-Boeing-777-300_PlanespottersNet_195477.jpg",
				logo:"http://thejetsetpets.com/wp-content/uploads/2012/07/air-france-logo-abbreviated.jpg",
				gateId:"7",
				flightNo:"AF-195",
				arrivalFlightNo:"AF-194",
				origin:"Paris(CDG)",
				destination:"Paris (CDG)",
				operator:"Air France",
				startTime:"21:40",
				endTime:"23:40",
				itenary:''
			},{
				airline:"China Airlines",
				serialNo:"B-18051",
				airdraftType:"777-300ER",
				img:"http://img1.jetphotos.net:8080/img/5/1/3/1/45935_1407807131.jpg",
				logo:"https://ideasinspiringinnovation.files.wordpress.com/2010/10/logo_china-airlines_tw-1.jpg?w=150&h=150",
				gateId:"7",
				flightNo:"CI-0005",
				arrivalFlightNo:"CI-0004",
				origin:"Taipei (TPE)",
				destination:"Taipei (TPE)",
				operator:"China Airlines",
				startTime:"12:40",
				endTime:"14:40",
				itenary:''
			},{
				airline:"China Southern Airlines",
				serialNo:"B-2099",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/441000/original/PlanespottersNet_441453.jpg",
				logo:"http://www.navjot-singh.com/uploads/3/1/7/4/3174873/1743190_orig.jpg?1",
				gateId:"7",
				flightNo:"CSN-304",
				arrivalFlightNo:"CSN-305",
				origin:"Shanghai(PVG)",
				destination:"Shanghai(PVG)",
				operator:"China Southern Airlines",
				startTime:"16:55",
				endTime:"18:55",
				itenary:''
			},{
				airline:"Turkish Airlines",
				serialNo:"TC-JJS",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/594000/original/TC-JJS-Turkish-Airlines-Boeing-777-300_PlanespottersNet_594665.jpg",
				logo:"http://d33gqm9lw3yglq.cloudfront.net/ProductImages/TellUs/TellUs_9885_23_large.jpg",
				gateId:"4",
				flightNo:"TK-522",
				arrivalFlightNo:"TK-521",
				origin:"Istanbul (IST)",
				destination:" Istanbul (IST)",
				operator:"Turkish Airlines",
				startTime:"12:30",
				endTime:"14:30",
				itenary:''
			},{
				airline:"Egypt Air",
				serialNo:"SU-GDR",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/482000/original/SU-GDR-EgyptAir-Boeing-777-300_PlanespottersNet_482013.jpg",
				logo:"http://img2.wikia.nocookie.net/__cb20100510190957/logopedia/images/c/c4/Egyptair_logo.svg",
				gateId:"5",
				flightNo:"MS-969",
				arrivalFlightNo:"MS-968",
				origin:"Cairo (CAI)",
				destination:"Cairo (CAI)",
				operator:"Egypt Air",
				startTime:"13:00",
				endTime:"15:00",
				itenary:''
			},{
				airline:"Thai Airways",
				serialNo:"HS-TKU",
				airdraftType:"777-300ER",
				img:"http://cdn.airplane-pictures.net/images/uploaded-images/2014/1/18/355929.jpg",
				logo:"http://skift.com/wp-content/uploads/2013/10/thaiairline-1092x1024.jpg",
				gateId:"5",
				flightNo:"TR-326",
				arrivalFlightNo:"TR-325",
				origin:"Bangkok (BKK) ",
				destination:"Bangkok (BKK) ",
				operator:"Thai Airways",
				startTime:"10:30",
				endTime:"12:30",
				itenary:''
			},{
				airline:"Air China",
				serialNo:"B-2006",
				airdraftType:"777-300ER",
				img:"https://c2.staticflickr.com/6/5461/17232559302_070fdbbd01_b.jpg",
				logo:"http://creativeroots.org/wp-content/uploads/2010/12/Air-China-identity1.png",
				gateId:"4",
				flightNo:"CA-062",
				arrivalFlightNo:"CA-061",
				origin:" Beijing (PEK) ",
				destination:" Beijing (PEK) ",
				operator:"Air China",
				startTime:"19:15",
				endTime:"21:15",
				itenary:''
			},{
				airline:"ANA",
				serialNo:"JA734A",
				airdraftType:"777-300ER",
				img:"https://c1.staticflickr.com/9/8420/8707266016_dbaf064120_b.jpg",
				logo:"https://s-media-cache-ak0.pinimg.com/236x/6e/91/79/6e9179536cefd250b4860a78905620c0.jpg",
				gateId:"6",
				flightNo:"NH-827",
				arrivalFlightNo:"NH-826",
				origin:"Tokyo-Narita (NRT)",
				destination:"Tokyo-Narita (NRT)",
				operator:"ANA",
				startTime:"08:16",
				endTime:"10:16",
				itenary:''
			},{
				airline:"ANA",
				serialNo:"JA777A",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/450000/original/JA777A-All-Nippon-Airways-Boeing-777-300_PlanespottersNet_450123.jpg",
				logo:"https://s-media-cache-ak0.pinimg.com/236x/6e/91/79/6e9179536cefd250b4860a78905620c0.jpg",
				gateId:"6",
				flightNo:"NH-829",
				arrivalFlightNo:"NH-828",
				origin:"Tokyo-Haneda (HND)",
				destination:"Tokyo-Haneda (HND)",
				operator:"ANA",
				startTime:"10:21",
				endTime:"12:21",
				itenary:''
			},{
				airline:"ANA",
				serialNo:"JA801A",
				airdraftType:"787-8",
				img:"http://cdn.airplane-pictures.net/images/uploaded-images/2011/9/2/154291.jpg",
				logo:"https://s-media-cache-ak0.pinimg.com/236x/6e/91/79/6e9179536cefd250b4860a78905620c0.jpg",
				gateId:"6",
				flightNo:"NH-831",
				arrivalFlightNo:"NH-830",
				origin:"Osaka (KIX)",
				destination:"Osaka (KIX)",
				operator:"ANA",
				startTime:"16:25",
				endTime:"18:25",
				itenary:''
			},{
				airline:"Air New Zealand",
				serialNo:"ZK-OKS",
				airdraftType:"777-300ER",
				img:"http://2.bp.blogspot.com/-i1-iwK1gLDc/VDpHrrvNNmI/AAAAAAAAIuU/uvo3S9XQmLw/s1600/WM%2BB777-300%2BZK-OKS%2BAKL%2B8.jpg",
				logo:"http://www.airnztravelagent.com/sites/default/files/styles/airnz_media_article_thumb/public/127x121_Koru.jpg?itok=YuM74BVa",
				gateId:"6",
				flightNo:"NZ-0001",
				arrivalFlightNo:"NZ-0071",
				origin:" Aukland (AUK)",
				destination:"London (LHR)",
				operator:"Air New Zealand",
				startTime:"19:00",
				endTime:"21:00",
				itenary:''
			},{
				airline:"Air New Zealand",
				serialNo:"ZK-OKO",
				airdraftType:"777-300ER",
				img:"http://img.planespotters.net/photo/446000/original/ZK-OKO-Air-New-Zealand-Boeing-777-300_PlanespottersNet_446689.jpg",
				logo:"http://www.airnztravelagent.com/sites/default/files/styles/airnz_media_article_thumb/public/127x121_Koru.jpg?itok=YuM74BVa",
				gateId:"7",
				flightNo:"NZ-0002",
				arrivalFlightNo:"NZ-0072",
				origin:"London (LHR)",
				destination:"Aukland (AUK)",
				operator:"Air New Zealand",
				startTime:"19:05",
				endTime:"21:05",
				itenary:''
			},{
				airline:"Air New Zealand",
				serialNo:"ZK-OKP",
				airdraftType:"777-300ER",
				img:"http://www.airlinereporter.com/wp-content/uploads/2013/11/1.jpg",
				logo:"http://www.airnztravelagent.com/sites/default/files/styles/airnz_media_article_thumb/public/127x121_Koru.jpg?itok=YuM74BVa",
				gateId:"6",
				flightNo:"NZ-0004",
				arrivalFlightNo:"NZ-0074",
				origin:"Paris (CDG)",
				destination:"Aukland (AUK)",
				operator:"Air New Zealand",
				startTime:"14:15",
				endTime:"16:15",
				itenary:''
			},{
				airline:"Air New Zealand",
				serialNo:"ZK-NZE",
				airdraftType:"787-9",
				img:"http://img.planespotters.net/photo/492000/original/ZK-NZE-Air-New-Zealand-Boeing-787-9-Dreamliner_PlanespottersNet_492119.jpg",
				logo:"http://www.airnztravelagent.com/sites/default/files/styles/airnz_media_article_thumb/public/127x121_Koru.jpg?itok=YuM74BVa",
				gateId:"6",
				flightNo:"NZ-0003",
				arrivalFlightNo:"NZ-0073",
				origin:"Aukland (AUK)",
				destination:"Paris (CDG)",
				operator:"Air New Zealand",
				startTime:"12:05",
				endTime:"14:05",
				itenary:''
			},{
				airline:"Air Canada",
				serialNo:"C-GHPQ",
				airdraftType:"787-8",
				img:"http://img.planespotters.net/photo/453000/original/C-GHPQ-Air-Canada-Boeing-787-8-Dreamliner_PlanespottersNet_453715.jpg",
				logo:"http://www.brandsoftheworld.com/sites/default/files/styles/logo-thumbnail/public/0021/6847/brand.gif?itok=KNALbaPN",
				gateId:"6",
				flightNo:"AC-152",
				arrivalFlightNo:"AC-151",
				origin:"London (LHR)",
				destination:"London (LHR)",
				operator:"United Airlines",
				startTime:"21:30",
				endTime:"23:30",
				itenary:''
			},{
				airline:"Eva Air",
				serialNo:"B-16701",
				airdraftType:"777-300ER",
				img:"http://www.hospitalitynet.org/picture/153047182.jpg",
				logo:"http://centreforaviation.com/images/resized/stories/companies/airlines/eva_air/evaairlogo-200x.png",
				gateId:"4",
				flightNo:"BR-0036",
				arrivalFlightNo:"BR-0035",
				origin:"Taipei (TPE)",
				destination:"Taipei (TPE)",
				operator:"Eva Air",
				startTime:"10:20",
				endTime:"12:20",
				itenary:''
			},{
				airline:"Eva Air",
				serialNo:"B-16718",
				airdraftType:"777-300ER",
				img:"https://c2.staticflickr.com/4/3770/13557283893_c14b9ced4d_b.jpg",
				logo:"http://centreforaviation.com/images/resized/stories/companies/airlines/eva_air/evaairlogo-200x.png",
				gateId:"4",
				flightNo:"BR-0010",
				arrivalFlightNo:"BR-0009",
				origin:"Taipei (TPE)",
				destination:"Taipei (TPE)",
				operator:"Eva Air",
				startTime:"21:45",
				endTime:"23:45",
				itenary:''
			},{
				airline:"Scoot Airlines",
				serialNo:"9V-OJA",
				airdraftType:"787-9",
				img:"https://worldairlinenews.files.wordpress.com/2015/02/scoot-787-9-9v-oja-12nosescootlr.jpg",
				logo:"http://static.planespotters.net/media/images/airlines/Scoot.png",
				gateId:"5",
				flightNo:"TZ-007",
				arrivalFlightNo:"TZ-006",
				origin:"Singapore(SIN)",
				destination:"Singapore(SIN)",
				operator:"Scoot Airlines",
				startTime:"16:00",
				endTime:"18:00",
				itenary:''
			},{
				airline:"Singapore Airlines",
				serialNo:"9V-SWA",
				airdraftType:"777-300ER",
				img:"https://upload.wikimedia.org/wikipedia/commons/1/1a/Singapore_Airlines_B773_9V-SWA.jpg",
				logo:"http://www.milesfortrips.com/wp-content/uploads/2015/01/singapore-airlines-logo.jpg",
				gateId:"5",
				flightNo:"SQ-002",
				arrivalFlightNo:"SQ-501",
				origin:"Singapore (SIN)",
				destination:"Frankfurt (FRA)",
				operator:"Singapore Airlines",
				startTime:"08:10",
				endTime:"10:10",
				itenary:''
			},{
				airline:"Singapore Airlines",
				serialNo:"9V-SYK",
				airdraftType:"777-300",
				img:"http://img.planespotters.net/photo/248000/original/9V-SYK-Singapore-Airlines-Boeing-777-300_PlanespottersNet_248357.jpg",
				logo:"http://www.milesfortrips.com/wp-content/uploads/2015/01/singapore-airlines-logo.jpg",
				gateId:"4",
				flightNo:"SQ-504",
				arrivalFlightNo:"SQ-003",
				origin:"Frankfurt (FRA)",
				destination:"Singapore (SIN)",
				operator:"Singapore Airlines",
				startTime:"08:15",
				endTime:"10:15",
				itenary:''
			},{
				airline:"Singapore Airlines",
				serialNo:"9V-SYL",
				airdraftType:"777-300",
				img:"http://img.planespotters.net/photo/310000/original/9V-SYL-Singapore-Airlines-Boeing-777-300_PlanespottersNet_310803.jpg",
				logo:"http://www.milesfortrips.com/wp-content/uploads/2015/01/singapore-airlines-logo.jpg",
				gateId:"5",
				flightNo:"SQ-503",
				arrivalFlightNo:"SQ-502",
				origin:"Singapore (SIN)",
				destination:"Singapore (SIN)",
				operator:"Singapore Airlines",
				startTime:"22:00",
				endTime:"23:59",
				itenary:''
			},{
				airline:"Aeroflot",
				serialNo:"VQ-BQG",
				airdraftType:"777-300ER",
				img:"https://c4.staticflickr.com/4/3915/14567030194_2e54bbc20d_b.jpg",
				logo:"http://centreforaviation.com/images/resized/stories/companies/airlines/aeroflot/aeroflot_logo-200x.png",
				gateId:"7",
				flightNo:"AFL-233",
				arrivalFlightNo:"AFL-232",
				origin:"Moscow (SVO)",
				destination:"Moscow (SVO)",
				operator:"Aeroflot",
				startTime:"19:10",
				endTime:"21:10",
				itenary:''
			},{
				airline:"Asiana Airlines",
				serialNo:"HL7732",
				airdraftType:"777-200ER",
				img:"http://img.planespotters.net/photo/211000/original/HL7732-Asiana-Airlines-Boeing-777-200_PlanespottersNet_211749.jpg",
				logo:"http://beijingcream.com/wp-content/uploads/2013/07/Asiana-Airlines-logo.png",
				gateId:"4",
				flightNo:"AAR-502",
				arrivalFlightNo:"AAR-501",
				origin:"Seoul (ICN)",
				destination:"Seoul (ICN)",
				operator:"Asiana Airlines",
				startTime:"16:45",
				endTime:"18:45",
				itenary:''
			}
		];
		return flightDetails;
	}
}


module.exports = FLightDetails;